<?php

/**
 * Implementation of hook_init()
 */
function commentsanity_init() {
  global $conf;
  $types = array_keys(node_get_types('names'));
  foreach($types as $type) {
    if (!isset($conf['comment_default_order_' . $type])) {
      $conf['comment_default_order_' . $type] = COMMENT_ORDER_OLDEST_FIRST;
    }
    $conf['comment_controls_' . $type] = COMMENT_CONTROLS_HIDDEN;
  }
}

function commentsanity_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'node_type_form' && isset($form['identity']['type'])) {
    //$form['comment']['comment_default_order']['#disabled'] = TRUE;
    //$form['comment']['comment_default_order']['#description'] .= ' ' . t('<em>Disabled by Comment Sanity module.</em>');
    $form['comment']['comment_controls']['#disabled'] = TRUE;
    $form['comment']['comment_controls']['#description'] .= ' ' . t('<em>Disabled by Comment Sanity module.</em>');
    $form['comment']['comment_default_mode']['#options'] = array(
      COMMENT_MODE_FLAT_EXPANDED => t('Flat (chronological)'),
      COMMENT_MODE_THREADED_EXPANDED => t('Threaded (replies appear together)')
    );
    $form['comment']['comment']['#options'] = array(
      COMMENT_NODE_DISABLED => t('Disabled'),
      COMMENT_NODE_READ_WRITE => t('Enabled')
    );

  }
}
